[package]
name = "e34"
version = "0.1.0"
authors = ["thor"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_bench"
harness = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
